name: Release

on:
  push:
    tags:
      - 'patch-*'
      - 'minor-*'
      - 'major-*'

jobs:
  release:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Determine version type
        id: version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [[ $TAG_NAME == patch-* ]]; then
            echo "type=patch" >> $GITHUB_OUTPUT
          elif [[ $TAG_NAME == minor-* ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
          elif [[ $TAG_NAME == major-* ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
          fi

      - name: Git status
        run: git status    
          
      - name: Run release-it
        run: pnpm release-it ${{ steps.version.outputs.type }} --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
